       ------------------ASSIGNMENT ON PROJECTION---------------
----1.	WAQTD ALL THE DETAILS FROM THE EMPLOYEE TABLE.
    SELECT  * 
    FROM  EMP ;
----2.	WAQTD NAMES OF ALL THE EMPLOYEES.
   SELECT  ENAME
   FROM  EMP ;
----3.	WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.
  SELECT  ENAME , SAL
  FROM  EMP ;
----4.	WAQTD NAME AND COMMISSION GIVEN TO ALL THE EMPLOYEES.
  SELECT  ENAME , COMM
  FROM  EMP ;
----5.	WAQTD EMPLOYEE ID AND DEPARTMENT NUMBER OF ALL THE EMPLOYEES IN EMP TABLE.
  SELECT  EMPNO , DEPTNO
  FROM  EMP  ;
----6.	WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES.
  SELECT  ENAME , HIREDATE
  FROM  EMP ;
----7.	WAQTD NAME AND DESIGNATION OF ALL THE EMPLPOYEES.
  SELECT  ENAME , JOB
  FROM  EMP ;
----8.	WAQTD NAME, JOB AND SALARY GIVEN ALL THE EMPLOYEES.
  SELECT  ENAME , JOB , SAL
  FROM  EMP ;
----9.	WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.
  SELECT  DNAME
  FROM  DEPT ;
----10.	WAQTD DNAME AND LOCATION PRESENT IN DEPT TABLE.
  SELECT  DNAME , LOC
  FROM  DEPT ;
----11.	WAQTD ALL THE DETAILS ALONG WITH EMPLOYEE_NAME
  SELECT EMP . * , ENAME
  FROM  EMP ;
----12.	WAQTD ALL THE DETAILS ALONG WITH MANAGER, JOB, SALARY.
  SELECT  EMP . * ,MGR , JOB , SAL
  FROM  EMP ;
----13.	WAQTD ALL THE DETAILS ALONG WITH DEPARTMENT NAMES.
SELECT DEPT . * , DNAME
FROM  DEPT ;
----14.	WAQTD NAMES, MANAGER_ID, JOB AND COMMISION OF EMPLOYEES.
SELECT  ENAME , MGR , JOB , COMM
FROM  EMP ;
----15.	WAQTD JOB, SALARY, COMMISION, NAMES OF EMPLOYEES.
SELECT JOB ,  SAL , COMM , ENAME
FROM  EMP ; 
